name: townerapp
description: Mobile Application for Drivers.

version: 1.0.0+3

environment:
  sdk: '>3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl:
  shared_preferences: ^2.2.2
  logger: ^2.2.0
  dio: ^5.4.1
  provider: 

  firebase_messaging: 
  cloud_firestore: 
  firebase_core: 
  firebase_database: 
  firebase_analytics:
  firebase_auth:
  geocoding: 
  google_maps_flutter: 
  geolocator:
  fluttertoast: 
  percent_indicator: 
  flutter_speed_dial: 
  flutter_slidable: 
  step_progress_indicator: 
  flutter_rating_bar: 
  dotted_border: 

  image_picker: 
  file_picker: 
  flutter_pdfview: 

  qr_flutter:
  flutter_share: ^2.0.0
  flutter_barcode_scanner: ^2.0.0
  timeline_tile:

  flutter_background_service: 
  flutter_local_notifications: 
  flutter_background_service_ios: 
  flutter_background_service_android: ^6.2.2
  permission_handler:

  lottie: 
  sms_autofill: 
  carousel_slider:
  syncfusion_flutter_charts:
  url_launcher: 
  flutter_contacts:
  socket_io_client:
  device_info_plus: ^9.1.1
  package_info_plus:
  pretty_dio_logger:
  get:

dependency_overrides:
  win32: ^5.5.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/towner_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: ""
    background_color: "#FFF"
    theme_color: "#FFF"
  windows:
    generate: true
    image_path: "assets/logo/towner_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/towner_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - assets/icons/
    - assets/logo/
    - assets/images/
    - assets/images/bottomBar/
    - assets/images/community/
    - assets/images/intro/
    - assets/images/ownerFeature/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  #
  # To generate flutter launcher icons run the following command
  # flutter pub run flutter_launcher_icons
  #
  # To generate the lagnuage files run the following command
  # flutter gen-l10n