// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG51XV2x1iomFLHEGzu_wevEuUmgCwF2o',
    appId: '1:460404902129:web:c74b6e80abe1196f234150',
    messagingSenderId: '460404902129',
    projectId: 'towner-mobile-dev',
    authDomain: 'towner-mobile-dev.firebaseapp.com',
    databaseURL: 'https://towner-mobile-dev-default-rtdb.firebaseio.com',
    storageBucket: 'towner-mobile-dev.appspot.com',
    measurementId: 'G-YNW3TR2LHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB20l46mtWY61Qf0SC_hbrgG2nQt9tOI-k',
    appId: '1:460404902129:android:bd61c228baa574c0234150',
    messagingSenderId: '460404902129',
    projectId: 'towner-mobile-dev',
    databaseURL: 'https://towner-mobile-dev-default-rtdb.firebaseio.com',
    storageBucket: 'towner-mobile-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGyAzC2dzpuuLiA-kaVSmxOldUWdc93fI',
    appId: '1:460404902129:ios:bcb8bf056284f081234150',
    messagingSenderId: '460404902129',
    projectId: 'towner-mobile-dev',
    databaseURL: 'https://towner-mobile-dev-default-rtdb.firebaseio.com',
    storageBucket: 'towner-mobile-dev.appspot.com',
    iosBundleId: 'com.towner.app.townerapp',
  );

}